# Generated by Django 2.2.12 on 2022-05-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tital', models.CharField(max_length=20)),
                ('descripation', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
