# Generated by Django 2.2.12 on 2022-05-06 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='tital',
            new_name='title',
        ),
    ]
