# Generated by Django 2.2.12 on 2022-05-06 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_todo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
    ]
